### ISSUE TITLE
Quiet option?

### ISSUE THREAD

**Issue by dgleba** [pjotrp/bioruby-table#30]
Is there a quiet option to tel bio-table to suppress informational messages?

> /home/file/cmm/ST-HP-GAGEMAX/50-2407 -04- Mach Op 35 Firstoff LO RC 669-E 2017-3-5 4_43_58 pm.txt  ...Processing file...
bio-table 1.0.0 Copyright (C) 2012-2014 Pjotr Prins <pjotr.prins@thebird.nl>

> INFO bio-table: Array: [{:show_help=>false, :write_header=>true, :skip=>0, :pad_fields=>true, :columns=>["0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "19", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "19", "19", "19", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40"]}]
 >INFO bio-table: Array: ["planid", "partnb", "id", "type", "idsymbol", "actual", "nominal", "uppertol", "lowertol", "deviation", "exceed", "featureid", "featuresigma", "comment", "link", "linkmode", "mmc", "useruppertol", "userlowertol", "fftphi", "fftphiunit", "zoneroundnessangle", "groupname", "groupname2", "datumAid", "datumBid", "datumCid", "featurePosX", "featurePosY", "featurePosZ", "group1", "group2", "group3", "group4", "group5", "group6", "group7", "group8", "group9", "group10", ""]

**Comment by pjotrp** [comment]
try bio-table --help. Since it is an INFO message I think quiet will do exactly that.
